### ISSUE TITLE
G Write to file error

### ISSUE THREAD

**Issue by gryBox** [gryBox/learning_map#151]
```
!!!!!!!!!!!!!I am in make_defnition.py to catch all the missing def errors!!!!!!!!!!!!!!!
IF Attribute error: prev_tt_corpus.text deos not exist
NO DEFINITION FOR KEYTERM: acdelco
Finished Making a Node. Time_to_make_node:  2.114004
!!!!!!!!!!!!!!!!EMPTY NODE .. NO Definition or No Teaching addresses!!!!!!!!!!!!!!!
'NoneType' object has no attribute 'stats_df'
Could not add node stats and corpus to G
Traceback (most recent call last):
  File "C:\Users\ilivni\Dropbox\GrayBox\App\appCode\learning_map\main.py", line 22, in <module>
    raw_lrnMap.make_lmap()
  File "C:\Users\ilivni\Dropbox\GrayBox\App\appCode\learning_map\make_learning_map.py", line 86, in make_lmap
    self.make_node_for_learning_map()
  File "C:\Users\ilivni\Dropbox\GrayBox\App\appCode\learning_map\make_learning_map.py", line 115, in make_node_for_learning_map
    self.to_file()
  File "C:\Users\ilivni\Dropbox\GrayBox\App\appCode\learning_map\make_learning_map.py", line 128, in to_file
    nx.write_gpickle(self.G, self.g_flpth)
  File "<decorator-gen-286>", line 2, in write_gpickle
  File "C:\Anaconda3\lib\site-packages\networkx\utils\decorators.py", line 198, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
OSError: [Errno 22] Invalid argument: 'C:/Users/ilivni/Dropbox/GrayBox/App/data//LEARNING_MAPS/64B66Bencoding/g.gpickle'
[Finished in 17502.8s with exit code 1]
```

**Comment by gryBox** [comment]
This was result of writing in python 3.5 and reading in 3.6
